// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transport.proto

package transport

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServMSG struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServMSG) Reset()         { *m = ServMSG{} }
func (m *ServMSG) String() string { return proto.CompactTextString(m) }
func (*ServMSG) ProtoMessage()    {}
func (*ServMSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{0}
}

func (m *ServMSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServMSG.Unmarshal(m, b)
}
func (m *ServMSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServMSG.Marshal(b, m, deterministic)
}
func (m *ServMSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServMSG.Merge(m, src)
}
func (m *ServMSG) XXX_Size() int {
	return xxx_messageInfo_ServMSG.Size(m)
}
func (m *ServMSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ServMSG.DiscardUnknown(m)
}

var xxx_messageInfo_ServMSG proto.InternalMessageInfo

func (m *ServMSG) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ServMSG) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ServMSG) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ClientMSG struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Msg                  *ServMSG `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientMSG) Reset()         { *m = ClientMSG{} }
func (m *ClientMSG) String() string { return proto.CompactTextString(m) }
func (*ClientMSG) ProtoMessage()    {}
func (*ClientMSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{1}
}

func (m *ClientMSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMSG.Unmarshal(m, b)
}
func (m *ClientMSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMSG.Marshal(b, m, deterministic)
}
func (m *ClientMSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMSG.Merge(m, src)
}
func (m *ClientMSG) XXX_Size() int {
	return xxx_messageInfo_ClientMSG.Size(m)
}
func (m *ClientMSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMSG.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMSG proto.InternalMessageInfo

func (m *ClientMSG) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *ClientMSG) GetMsg() *ServMSG {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*ServMSG)(nil), "transport.ServMSG")
	proto.RegisterType((*ClientMSG)(nil), "transport.ClientMSG")
}

func init() {
	proto.RegisterFile("transport.proto", fileDescriptor_a97e32c760ec1b28)
}

var fileDescriptor_a97e32c760ec1b28 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x29, 0x4a, 0xcc,
	0x2b, 0x2e, 0xc8, 0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x39, 0x73, 0xb1, 0x07, 0xa7, 0x16, 0x95, 0xf9, 0x06, 0xbb, 0x0b, 0xf1, 0x71, 0x31, 0x65, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x89, 0x70, 0xb1, 0x16, 0x14,
	0x65, 0x26, 0xa7, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x05, 0x41, 0x38, 0x42, 0x42, 0x5c, 0x2c,
	0x79, 0x89, 0xb9, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x37, 0x17,
	0xa7, 0x73, 0x4e, 0x66, 0x6a, 0x5e, 0x09, 0xc8, 0x18, 0x09, 0x2e, 0xf6, 0xe4, 0xa2, 0xd4, 0xc4,
	0x92, 0x54, 0x88, 0x59, 0x1c, 0x41, 0x30, 0xae, 0x90, 0x0a, 0x17, 0x73, 0x6e, 0x71, 0x3a, 0xd8,
	0x38, 0x6e, 0x23, 0x21, 0x3d, 0x84, 0xab, 0xa0, 0x2e, 0x08, 0x02, 0x49, 0x1b, 0xb9, 0x70, 0x71,
	0x07, 0xa7, 0xe6, 0xa5, 0x80, 0xc4, 0x40, 0xf6, 0x99, 0x82, 0x1c, 0x98, 0x97, 0x02, 0x32, 0x19,
	0x8b, 0x16, 0x29, 0x11, 0x24, 0x31, 0xb8, 0x1b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x3e, 0x35, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xea, 0x99, 0x7a, 0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SendServiceClient is the client API for SendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendServiceClient interface {
	SendMSG(ctx context.Context, in *ServMSG, opts ...grpc.CallOption) (*ClientMSG, error)
}

type sendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSendServiceClient(cc grpc.ClientConnInterface) SendServiceClient {
	return &sendServiceClient{cc}
}

func (c *sendServiceClient) SendMSG(ctx context.Context, in *ServMSG, opts ...grpc.CallOption) (*ClientMSG, error) {
	out := new(ClientMSG)
	err := c.cc.Invoke(ctx, "/transport.SendService/SendMSG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendServiceServer is the server API for SendService service.
type SendServiceServer interface {
	SendMSG(context.Context, *ServMSG) (*ClientMSG, error)
}

// UnimplementedSendServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSendServiceServer struct {
}

func (*UnimplementedSendServiceServer) SendMSG(ctx context.Context, req *ServMSG) (*ClientMSG, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMSG not implemented")
}

func RegisterSendServiceServer(s *grpc.Server, srv SendServiceServer) {
	s.RegisterService(&_SendService_serviceDesc, srv)
}

func _SendService_SendMSG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServMSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServiceServer).SendMSG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.SendService/SendMSG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServiceServer).SendMSG(ctx, req.(*ServMSG))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transport.SendService",
	HandlerType: (*SendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMSG",
			Handler:    _SendService_SendMSG_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport.proto",
}
